### ISSUE TITLE
Horse vanished after warp?

### ISSUE THREAD

**Issue by TheZenKitteh** [TheMrJezza/HorseTpWithMe#1]
So, it's no big deal but I gave myself a horse that was probably too fast. I was riding it around and found a village so I set a warp and warped back to the stable to drop off the horse. When I returned to the stable I couldn't get off the horse. After waiting a few minutes I logged out and back in and the horse was gone. Not in the stable or the village and I can't find him so I presume he despawned.

I'm only reporting this because this is the second time that horse glitched after a warp (using MyWarp). The first time a disconnect and a reconnect worked. The second time the horse vanished.

Bukkit 1.11.2
MyWarp mywarp-bukkit-3.0-beta-4
I also have the latest nocheatplus which complained a lot during my ride lol.

If this is a problem with HorseTpWithMe, would be nice to see it fixed. I would hate to hear of a player losing a prized horse due to some unknown issue. If it's not a problem with this plugin, you can ignore this.

Full log of the event:
18.07 01:11:35 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:11:35 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:11:35 [Server] WARN This Horse is Crazy! (vehicle of USERNAME) moved too quickly! -1651.9245402574502,-11.0,1375.448176408327 
18.07 01:11:46 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:28 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:28 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:28 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:36 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:36 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:36 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:37 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:37 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:37 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:37 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:12:37 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:13:05 [Server] WARN This Horse is Crazy! (vehicle of USERNAME) moved too quickly! -21.437707978812398,-0.26150779068264285,1.3840096751395663 
18.07 01:13:05 [Server] WARN This Horse is Crazy! (vehicle of USERNAME) moved too quickly! -22.489998795512065,-0.26150779068264285,1.443022666075933 
18.07 01:13:11 [Server] INFO [ClearLag] Warning Ground items will be removed in 60 seconds! 
18.07 01:13:21 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:13:21 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:13:22 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:13:22 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:13:51 [Server] INFO [ClearLag] Warning Ground items will be removed in 20 seconds! 
18.07 01:14:07 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:07 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:07 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:12 [Server] INFO [ClearLag] Removed 45 Entities! 
18.07 01:14:22 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:33 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:33 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:34 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:53 [Server] INFO USERNAME issued server command: /warp create village2 
18.07 01:14:57 [Server] INFO USERNAME issued server command: /warp horse 
18.07 01:14:57 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:57 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:14:57 [Server] WARN This Horse is Crazy! (vehicle of USERNAME) moved too quickly! 871.7764702380655,1.0,-1610.6734923117463 
18.07 01:14:57 [Server] WARN This Horse is Crazy! (vehicle of USERNAME) moved too quickly! 871.7764702380655,1.0,-1610.6734923117463 
18.07 01:14:57 [Server] WARN Wrong location! (-113, 76) should be (-59, -25), EntityHorse['This Horse is Crazy!'/40846, l='world1', x=-1802.19, y=69.00, z=1226.17] 
18.07 01:15:19 [Server] INFO USERNAME issued server command: /warp horse 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:19 [Server] WARN This Horse is Crazy! moved wrongly! 
18.07 01:15:30 [Server] INFO [g] [world1] [EdoCastle] Ninja Chief USERNAME: lol cant get off my horse 
18.07 01:15:46 [Disconnect] User USERNAME has disconnected, reason: Disconnected 
18.07 01:15:46 [Server] INFO USERNAME left the game 
18.07 01:15:54 [Server] INFO [WorldGuard] Region data changes made in 'world1' have been background saved
18.07 01:16:07 [Multicraft] Auto-saving world... 
18.07 01:16:07 [Server] INFO Saving is already turned on 
18.07 01:16:07 [Server] INFO Saving... 
18.07 01:16:08 [Server] INFO World saved.
(Then I logged in and noticed no horse anywhere)

**Comment by TheMrJezza** [comment]
Basically what you experienced is an issue where you Dismounted the horse on the server, but on your game client, you were still on the horse. Your horse wouldn't have despawned, it would still be where you first tried to dismount it. Because of this, every time you try to dismount the Horse afterward, the server doesn't allow it because it doesn't know you're still on the horse. When you rejoin the server, the client gets told that you are not on a horse and thus everything is normal. It usually happens when the VehicleExitEvent in Bukkit get's canceled (So plugins such as WorldGuard that try to stop players leaving their horses are known to cause it). I'm not exactly sure what's causing it for you, however, I will try to do what I can to fix it.

**Comment by TheMrJezza** [comment]
I actually have a video of what Im talking about. I recorded it when I reported this issue to Spigot over a year ago. https://www.youtube.com/watch?v=Q2tdrQQE8fM The video is low quality, but you can see what I mean
