### ISSUE TITLE
Teleport with non-horse

### ISSUE THREAD

**Issue by thisguy786** [TheMrJezza/HorseTpWithMe#12]
I noticed there are permissions to teleport many things including, for example, a goat.

Is it actually possible to do this?  If so, how?

Thanks!

**Comment by NotAlexNoyle** [comment]
horsetpwithme.teleport.*

This is on the main spigotmc page https://www.spigotmc.org/resources/horsetpwithme.8186/

**Comment by thisguy786** [comment]
I understand how the permissions work.

The question I have is how do you teleport an entity that isn't a vehicle?

**Comment by thisguy786** [comment]
I see.  You put the animal into a vehicle like a boat and *then* they come with you.

**Comment by TheMrJezza** [comment]
That is one solution, however, as far as Minecraft is concerned, every entity can have passengers, i.e. 'anything can be ridden'. By default, only a select few mobs can be controlled.. You can use plugins or modify your server code to enable mounting entities that are usually locked in vanilla.

HorseTpWithMe doesn't unlock that ability to mount all entities, but it does support teleporting all of them if you have already unlocked them by other means.
