### ISSUE TITLE
HorseTPwithMe is red in /pl upon new paper update

### ISSUE THREAD

**Issue by Castiella** [TheMrJezza/HorseTpWithMe#2]
Currently using this build of paper

#570 https://papermc.io/downloads

Which i installed this morning, upon restart HorseTP is red.

Server log:
[latest (6).log](https://github.com/TheMrJezza/HorseTpWithMe/files/2991806/latest.6.log)

console output on startup : [12:28:12 ERROR]: Error occurred while enabling HorseTpWithMe v3.2.0 (Is it up to date?)

I am using the most recent  build spigot offers :)

**Comment by TheMrJezza** [comment]
I believe that HorseTpWithMe isn't compatible with your version of Ridables. However in the next release of HorseTpWithMe, which will be very soon I assure you, the plugin won't need to be compatible.

**Comment by Castiella** [comment]
If its any help, this is why ridables is broken


BillyToday at 5:25 PM
Well, I seemed to have found the root cause. md_5 remapped nms mid version.. again.. :/ he's got to stop doing that shit. https://hub.spigotmc.org/stash/projects/SPIGOT/repos/builddata/commits
Now comes the painful task of cross referencing everything from vanilla to craftbukkit to spigot to paper then finally to ridables.
