### ISSUE TITLE
Bug preventing boat teleportation

### ISSUE THREAD

**Issue by Weasel-Beans** [TheMrJezza/HorseTpWithMe#4]
https://timings.aikar.co/?id=112e5ebd7ef64dd28a4d0fe29459c6d1

https://pastebin.com/MATUYNkt

While trying out the new update on my local test server, I noticed that teleporting with boats usually didn't work, and caused warnings to appear in the console.

**Comment by TheMrJezza** [comment]
I will take a look when I get home. Just letting you know I've seen the issue.

**Comment by TheMrJezza** [comment]
I just pushed a new update. As of version 7.4.0.0, this issue should be resolved. However, I recommend you use the latest version (currently v7.4.0.1).
